/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Solicitud;

import javax.swing.JOptionPane;

import org.json.simple.JSONObject;

import Clases.Json;
import Clases.ModeloTabla;
import Clases.Peticion;
import Principal.MenuPrincipal;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JDialog;

/**
 *
 * @author EN UN CLICK
 */
public class NuevaSolicitudReservacion extends javax.swing.JPanel {

    Json jsonSucursales;
    MenuPrincipal menuPrincipal;
    JDialog dialog;
    public NuevaSolicitudReservacion(MenuPrincipal menuPrincipal,JDialog dialog) {
        initComponents();
        jsonSucursales = new Json();
        this.menuPrincipal = menuPrincipal;
        this.dialog = dialog;
        obtenerSucursales();
    }

    private void obtenerSucursales() {
    	Thread hilo = new Thread(() -> {
    		comboboxRetiro.removeAllItems();
    		comboboxEntrega.removeAllItems();
			try {
				Json sucursal = Peticion.get(menuPrincipal.getInfo().getApiPath()+"/api/sucursal/", "");
				
				for (JSONObject data : sucursal.getArrayList()) {
					comboboxRetiro.addItem(data.get("ciudad")+" - "+data.get("sucursal"));
					comboboxEntrega.addItem(data.get("ciudad")+" - "+data.get("sucursal"));
				}
				
			}catch (Exception e) {
				// TODO: handle exception
			}
		});
		hilo.start();
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneldecoracion1 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtvin = new javax.swing.JTextField();
        jDateChooserEntrega = new com.toedter.calendar.JDateChooser();
        jDateChooserRetiro = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBoxServEntrega = new javax.swing.JCheckBox();
        jPaneldecoracion3 = new javax.swing.JPanel();
        jPaneldecoracion4 = new javax.swing.JPanel();
        jPaneldecoracion2 = new javax.swing.JPanel();
        comboboxRetiro = new javax.swing.JComboBox<>();
        comboboxEntrega = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPaneldecoracion5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServiciosExtras = new javax.swing.JTable();
        jPaneldecoracion6 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        btnX = new javax.swing.JButton();
        btnSeguroExistente = new javax.swing.JButton();
        btnNuevoSeguro1 = new javax.swing.JButton();
        btnNuevoSeguro1.addActionListener(v -> {
        	JDialog dialog = new JDialog(this.dialog,true);
        	dialog.setSize(1000,650);
        	dialog.setLocationRelativeTo(null);
        	dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        	dialog.getContentPane().add(new PanelNuevoSeguro(menuPrincipal));
        	dialog.setVisible(true);
        });
        btnguardar1 = new javax.swing.JButton();
        btnguardar1.addActionListener(v -> new DatosCliente(dialog).setVisible(true));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPaneldecoracion1.setBackground(new java.awt.Color(86, 89, 92));

        jLabel.setBackground(new java.awt.Color(255, 255, 255));
        jLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Nueva solicitud de reservación");

        javax.swing.GroupLayout jPaneldecoracion1Layout = new javax.swing.GroupLayout(jPaneldecoracion1);
        jPaneldecoracion1.setLayout(jPaneldecoracion1Layout);
        jPaneldecoracion1Layout.setHorizontalGroup(
            jPaneldecoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion1Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jPaneldecoracion1Layout.setVerticalGroup(
            jPaneldecoracion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPaneldecoracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Lugar de entrega");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 120, 16));

        txtvin.setBackground(new java.awt.Color(241, 232, 232));
        txtvin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtvin.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        add(txtvin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 200, -1));
        add(jDateChooserEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 190, -1));
        add(jDateChooserRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Vin:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 50, 16));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Fecha de retiro");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 120, 16));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Lugar de retiro");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 16));

        jCheckBoxServEntrega.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jCheckBoxServEntrega.setText("Servicio de entrega a domicilio");
        add(jCheckBoxServEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 210, -1));

        jPaneldecoracion3.setBackground(new java.awt.Color(86, 89, 92));

        javax.swing.GroupLayout jPaneldecoracion3Layout = new javax.swing.GroupLayout(jPaneldecoracion3);
        jPaneldecoracion3.setLayout(jPaneldecoracion3Layout);
        jPaneldecoracion3Layout.setHorizontalGroup(
            jPaneldecoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPaneldecoracion3Layout.setVerticalGroup(
            jPaneldecoracion3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        add(jPaneldecoracion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 30, 620));

        jPaneldecoracion4.setBackground(new java.awt.Color(86, 89, 92));

        javax.swing.GroupLayout jPaneldecoracion4Layout = new javax.swing.GroupLayout(jPaneldecoracion4);
        jPaneldecoracion4.setLayout(jPaneldecoracion4Layout);
        jPaneldecoracion4Layout.setHorizontalGroup(
            jPaneldecoracion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPaneldecoracion4Layout.setVerticalGroup(
            jPaneldecoracion4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        add(jPaneldecoracion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        jPaneldecoracion2.setBackground(new java.awt.Color(86, 89, 92));

        javax.swing.GroupLayout jPaneldecoracion2Layout = new javax.swing.GroupLayout(jPaneldecoracion2);
        jPaneldecoracion2.setLayout(jPaneldecoracion2Layout);
        jPaneldecoracion2Layout.setHorizontalGroup(
            jPaneldecoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPaneldecoracion2Layout.setVerticalGroup(
            jPaneldecoracion2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPaneldecoracion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, -1, 30));

        comboboxRetiro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboboxRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 190, -1));

        comboboxEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboboxEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 190, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Fecha de entrega");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 120, 16));

        jPaneldecoracion5.setBackground(new java.awt.Color(86, 89, 92));
        jPaneldecoracion5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Servicios extras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTableServiciosExtras.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableServiciosExtras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Descripcion", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jTableServiciosExtras);

        javax.swing.GroupLayout jPaneldecoracion5Layout = new javax.swing.GroupLayout(jPaneldecoracion5);
        jPaneldecoracion5.setLayout(jPaneldecoracion5Layout);
        jPaneldecoracion5Layout.setHorizontalGroup(
            jPaneldecoracion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneldecoracion5Layout.setVerticalGroup(
            jPaneldecoracion5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        add(jPaneldecoracion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 400, 460));

        jPaneldecoracion6.setBackground(new java.awt.Color(86, 89, 92));
        jPaneldecoracion6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Seguro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));

        btnX.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnX.setForeground(new java.awt.Color(33, 37, 41));
        btnX.setText("X");
        btnX.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSeguroExistente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSeguroExistente.setForeground(new java.awt.Color(33, 37, 41));
        btnSeguroExistente.setText("Seguro existente");
        btnSeguroExistente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnNuevoSeguro1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNuevoSeguro1.setForeground(new java.awt.Color(33, 37, 41));
        btnNuevoSeguro1.setText("Nuevo seguro");
        btnNuevoSeguro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPaneldecoracion6Layout = new javax.swing.GroupLayout(jPaneldecoracion6);
        jPaneldecoracion6.setLayout(jPaneldecoracion6Layout);
        jPaneldecoracion6Layout.setHorizontalGroup(
            jPaneldecoracion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnNuevoSeguro1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnSeguroExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPaneldecoracion6Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneldecoracion6Layout.setVerticalGroup(
            jPaneldecoracion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneldecoracion6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPaneldecoracion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnX, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPaneldecoracion6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoSeguro1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeguroExistente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        add(jPaneldecoracion6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 450, 200));

        btnguardar1.setBackground(new java.awt.Color(33, 37, 41));
        btnguardar1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnguardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnguardar1.setText("Guardar");
        btnguardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 110, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoSeguro1;
    private javax.swing.JButton btnSeguroExistente;
    private javax.swing.JButton btnX;
    private javax.swing.JButton btnguardar1;
    private javax.swing.JCheckBox jCheckBoxServEntrega;
    private javax.swing.JComboBox<String> comboboxRetiro;
    private javax.swing.JComboBox<String> comboboxEntrega;
    private com.toedter.calendar.JDateChooser jDateChooserEntrega;
    private com.toedter.calendar.JDateChooser jDateChooserRetiro;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPaneldecoracion1;
    private javax.swing.JPanel jPaneldecoracion2;
    private javax.swing.JPanel jPaneldecoracion3;
    private javax.swing.JPanel jPaneldecoracion4;
    private javax.swing.JPanel jPaneldecoracion5;
    private javax.swing.JPanel jPaneldecoracion6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableServiciosExtras;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtvin;
    // End of variables declaration//GEN-END:variables
}
