/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Solicitud;

import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;

import org.json.simple.JSONObject;

import Clases.ColorearFilasIntercaladas;
import Clases.Json;
import Clases.ModeloTabla;
import Clases.Peticion;
import Principal.MenuPrincipal;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.GroupLayout;

/**
 *
 * @author melvinorellana
 */
public class PanelNuevoSeguro extends javax.swing.JPanel {

	private MenuPrincipal menuPrincipal;
	public PanelNuevoSeguro(MenuPrincipal menuPrincipal) {
		this.menuPrincipal = menuPrincipal;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanelReservaciones = new javax.swing.JPanel();
		lblReservaciones = new javax.swing.JLabel();
		btnAgregarSeguro = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		TblCoberturaS = new javax.swing.JTable();

		jPanel1.setBackground(new java.awt.Color(204, 204, 204));

		jPanelReservaciones.setBackground(new java.awt.Color(102, 102, 102));
		jPanelReservaciones.setForeground(new java.awt.Color(255, 255, 255));

		lblReservaciones.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
		lblReservaciones.setForeground(new java.awt.Color(255, 255, 255));
		lblReservaciones.setText("Agregar Cobertura de Seguro");

		javax.swing.GroupLayout jPanelReservacionesLayout = new javax.swing.GroupLayout(jPanelReservaciones);
		jPanelReservaciones.setLayout(jPanelReservacionesLayout);
		jPanelReservacionesLayout.setHorizontalGroup(
				jPanelReservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanelReservacionesLayout.createSequentialGroup().addGap(446, 446, 446)
								.addComponent(lblReservaciones).addContainerGap(531, Short.MAX_VALUE)));
		jPanelReservacionesLayout.setVerticalGroup(
				jPanelReservacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanelReservacionesLayout.createSequentialGroup().addGap(20, 20, 20)
								.addComponent(lblReservaciones).addContainerGap(19, Short.MAX_VALUE)));

		btnAgregarSeguro.setText("Agregar Seguro");
		btnAgregarSeguro.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAgregarSeguroActionPerformed(evt);
			}
		});

		TblCoberturaS.setAutoCreateRowSorter(true);
		Thread hilo = new Thread(() -> {
			try {
				Json cobertura = Peticion.get(menuPrincipal.getInfo().getApiPath() + "/api/cobertura/", "");
				ModeloTabla model = new ModeloTabla(cobertura,
						new String[] { "", "nombre", "descripcion", "monto" },
						new String[] { "", "Descripcion", "Descripcion Detallada", "Monto" });
				
				TblCoberturaS.setModel(model);
				model.addCheckBox(0, TblCoberturaS);
				TblCoberturaS.getColumnModel().getColumn(0).setPreferredWidth(10);
				TblCoberturaS.getColumnModel().getColumn(1).setPreferredWidth(150);
				TblCoberturaS.getColumnModel().getColumn(2).setPreferredWidth(350);
				
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, e);
			}
		});
		hilo.start();
		TblCoberturaS.addMouseListener(new MouseAdapter() {
			public void mouseClicked(MouseEvent e) {
                int selectedRow = TblCoberturaS.getSelectedRow();
                Object isCheck = TblCoberturaS.getValueAt(selectedRow, 0);
                if(isCheck==null)isCheck = false;
                TblCoberturaS.setValueAt(!(boolean)isCheck, selectedRow, 0);
            }
		});
		TblCoberturaS.setColumnSelectionAllowed(true);
		TblCoberturaS.setRowHeight(28);
		TblCoberturaS.setDefaultRenderer(Object.class, new ColorearFilasIntercaladas(menuPrincipal.getInfo().getSecondColor(),menuPrincipal.getInfo().getPrimaryColor(),Color.white));
		jScrollPane2.setViewportView(TblCoberturaS);
		TblCoberturaS.getColumnModel().getSelectionModel()
				.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
		TblCoberturaS.getTableHeader().setFont(new Font("Arial Black", Font.BOLD, 14));

       

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(
										jPanelReservaciones, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(481)
										.addComponent(btnAgregarSeguro))
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(63).addComponent(jScrollPane2,
										GroupLayout.PREFERRED_SIZE, 809, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(
						jPanel1Layout
								.createParallelGroup(
										Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(jPanelReservaciones, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGap(18)
										.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE,
												GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGap(31).addComponent(btnAgregarSeguro)
										.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jPanel1,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGap(20, 20, 20)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	private void btnAgregarSeguroActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAgregarSeguroActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnAgregarSeguroActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTable TblCoberturaS;
	private javax.swing.JButton btnAgregarSeguro;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanelReservaciones;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JLabel lblReservaciones;
	// End of variables declaration//GEN-END:variables
}
